# Generated by Django 4.1.6 on 2023-02-14 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('RAW SQL CODE')
    ]
    
